// The generated OpenNext worker only exposes `fetch`. This wrapper keeps that
// handler and adds a cron fallback for durable outbox delivery.
// @ts-expect-error Generated by `pnpm cf:build` before Wrangler bundles this file.
import handler from "./.open-next/worker.js";
// @ts-expect-error Generated by `pnpm cf:build` before Wrangler bundles this file.
import { runWithCloudflareRequestContext } from "./.open-next/cloudflare/init.js";
import { processEmailOutboxBatch } from "./src/worker/emailProcessor";
import { runHousekeeping } from "./src/worker/housekeeping";
import { processOutboxBatch } from "./src/worker/processor";

type WorkerEnv = Record<string, unknown> & { APP_BASE_URL?: string };
type WorkerContext = {
  waitUntil(promise: Promise<unknown>): void;
};

async function runScheduledWork(env: WorkerEnv, ctx: WorkerContext): Promise<void> {
  const baseUrl = typeof env.APP_BASE_URL === "string" ? env.APP_BASE_URL : "https://oportfolio.invalid";
  const request = new Request(new URL("/__oportfolio/cron", baseUrl));

  await runWithCloudflareRequestContext(request, env, ctx, async () => {
    await processEmailOutboxBatch(50);
    // Process attachment scans and the rest of the durable outbox. Without
    // this, encrypted uploads remain pending forever and exports skip them.
    await processOutboxBatch(25);
    await runHousekeeping();
    return new Response(null, { status: 204 });
  });
}

const worker = {
  fetch(request: Request, env: WorkerEnv, ctx: WorkerContext): Promise<Response> {
    return handler.fetch(request, env, ctx);
  },

  scheduled(_event: unknown, env: WorkerEnv, ctx: WorkerContext): void {
    ctx.waitUntil(runScheduledWork(env, ctx));
  },
};

export default worker;

// Required if OpenNext's Durable Object cache is enabled later.
// @ts-expect-error Generated by `pnpm cf:build` before Wrangler bundles this file.
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
